language: python
python: 3.7

env:
  global:
    - PY_VERSIONS="3.8.1 3.7.4 3.6.8 3.5.4"
    - PYPI_REPOSITORY_URL=https://upload.pypi.org/legacy/
    - PYPI_USERNAME=__token__
    - secure: "jfAnPdxjTDw/mFbM2rmqjHaBtGpA+Rr+goCB5/Jp6RZ5N2M60nJliw8B5v7RwZDy//nSIdbTBU7cF/7WjEPwzrHUn5LQsS13ThzoS6KE7NUPa77TOxEpHXr4MJsyeSQMindEbAMeYP+lffI8/ISQ85evIbbSn6XzZSN/YBpQCTUGHWViqKIlpT70GYfRTeEJ0YvXxcJHKXoMuG7N80n8DW88FlfuI2age29cAe80pNn2yCZww2ZH0kG62HGQhzVv4v/uvxLLTaDP/JndYQyBnw6y5gesT2XCrgmCPgCTyVrtJsR96LjOukG2/T5etgpK0sgRwfgRk2DjKmlUqQOUm57lO+52ECaqqbaERFYe/Ub4JZ4DD05lKqm6wtQMD+fYl+TLKzGvCWayuLvxs7HqI+cz0BQQ7iynXuPUqX3xpkUDdAUzg9remmEJ1n8WG/NMHsv3Embh6zHS9RW7OUBXTELjrgJHVwjm8N0KtY063kMDArlSLNcf1gUPOx8MTOXBQWcauxmLfXMyaWrjHQ++1dWRFWjNVkUWfv+l17/ZHJHHnaJ6VpzhrZ5uku4LfEH8hgOCL6EYbO1PVXuEvFXDQX6wIFdbXaXSkx78ZgfiJf3xDqxcU1jl7+ipoCe2xkXaRkka0wg1gwCsfF53suXGIEIMRBWqrGJI9vETu5mVQDY="

deploy:
  provider: script
  skip_cleanup: true
  script: bash .ci/deploy.sh
  on:
    tags: true
    condition: $DEPLOY = 1

jobs:
  include:
    - stage: build
      name: OSX
      os: osx
      osx_image: xcode9.2  # macOS 10.12, oldest supported version
      language: generic
      env:
        - DEPLOY=1
      script: bash .ci/build-osx.sh
      before_deploy:
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv global 3.7.4
      before_cache:
        - brew cleanup
        - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
        - find $HOME/.pyenv/ -name '*.pyc' -delete
      cache:
        directories:
          - $HOME/.pyenv/
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew

    - stage: build
      name: Windows
      os: windows
      language: c
      env:
        - DEPLOY=1
      script: bash .ci/build-windows.sh
      before_deploy:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - bash .ci/deploy.sh

    - stage: build
      name: Manylinux x86_64
      services: docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        - PLAT=manylinux1_x86_64
        - DEPLOY=1
      script: bash .ci/build-manylinux.sh

    - stage: build
      name: Manylinux i686
      services: docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
        - PRE_CMD=linux32
        - PLAT=manylinux1_i686
        - DEPLOY=1
      script: bash .ci/build-manylinux.sh

    - stage: build
      name: Coverage
      os: linux
      script: bash .ci/coverage.sh

    - stage: build
      name: Performance
      os: linux
      script: bash .ci/performance.sh

    - stage: build
      name: Source distribution
      os: linux
      env:
        - DEPLOY=1
      script: bash .ci/build-linux-sdist.sh
